//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Inaeba_SaptraEntities : DbContext
    {
        public Inaeba_SaptraEntities()
            : base("name=Inaeba_SaptraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cCoordinacionesRegion> cCoordinacionesRegion { get; set; }
        public virtual DbSet<cCoordinacionesZona> cCoordinacionesZona { get; set; }
        public virtual DbSet<cEstatus> cEstatus { get; set; }
        public virtual DbSet<cPeriodos> cPeriodos { get; set; }
        public virtual DbSet<cTipoActividades> cTipoActividades { get; set; }
        public virtual DbSet<cTipoEstatus> cTipoEstatus { get; set; }
        public virtual DbSet<cTipoFiguras> cTipoFiguras { get; set; }
        public virtual DbSet<cTipoNotificaciones> cTipoNotificaciones { get; set; }
        public virtual DbSet<cTiposUsuario> cTiposUsuario { get; set; }
        public virtual DbSet<mLecturaCertificados> mLecturaCertificados { get; set; }
        public virtual DbSet<mCoordinacionRegionZonaUsuario> mCoordinacionRegionZonaUsuario { get; set; }
        public virtual DbSet<mCoordinacionZonaUsuario> mCoordinacionZonaUsuario { get; set; }
        public virtual DbSet<mEducandosCaptados> mEducandosCaptados { get; set; }
        public virtual DbSet<CertificadosProgramados> CertificadosProgramados { get; set; }
        public virtual DbSet<InaebaPreregistros> InaebaPreregistros { get; set; }
        public virtual DbSet<dDetallePlanSemanal> dDetallePlanSemanal { get; set; }
        public virtual DbSet<mCheckIn> mCheckIn { get; set; }
        public virtual DbSet<mPlanSemanal> mPlanSemanal { get; set; }
        public virtual DbSet<dModulos> dModulos { get; set; }
        public virtual DbSet<mBitacora> mBitacora { get; set; }
        public virtual DbSet<mMenuGrupo> mMenuGrupo { get; set; }
        public virtual DbSet<mPermisos> mPermisos { get; set; }
        public virtual DbSet<mRoles> mRoles { get; set; }
        public virtual DbSet<mNotificaciones> mNotificaciones { get; set; }
        public virtual DbSet<mResetPassword> mResetPassword { get; set; }
        public virtual DbSet<mUsuarios> mUsuarios { get; set; }
        public virtual DbSet<mSolicitudesVehiculo> mSolicitudesVehiculo { get; set; }
    
        [DbFunction("Entities", "Split")]
        public virtual IQueryable<Split_Result> Split(string strString)
        {
            var strStringParameter = strString != null ?
                new ObjectParameter("strString", strString) :
                new ObjectParameter("strString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[Entities].[Split](@strString)", strStringParameter);
        }
    
        [DbFunction("Entities", "udf_CertificadosInaebaBaseList")]
        public virtual IQueryable<udf_CertificadosInaebaBaseList_Result> udf_CertificadosInaebaBaseList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_CertificadosInaebaBaseList_Result>("[Entities].[udf_CertificadosInaebaBaseList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_CertificadosInaebaFiguraEducandoList")]
        public virtual IQueryable<udf_CertificadosInaebaFiguraEducandoList_Result> udf_CertificadosInaebaFiguraEducandoList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_CertificadosInaebaFiguraEducandoList_Result>("[Entities].[udf_CertificadosInaebaFiguraEducandoList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_CertificadosInaebaRegionList")]
        public virtual IQueryable<udf_CertificadosInaebaRegionList_Result> udf_CertificadosInaebaRegionList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_CertificadosInaebaRegionList_Result>("[Entities].[udf_CertificadosInaebaRegionList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_CertificadosInaebaZonaFiguraList")]
        public virtual IQueryable<udf_CertificadosInaebaZonaFiguraList_Result> udf_CertificadosInaebaZonaFiguraList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_CertificadosInaebaZonaFiguraList_Result>("[Entities].[udf_CertificadosInaebaZonaFiguraList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_CertificadosInaebaZonaList")]
        public virtual IQueryable<udf_CertificadosInaebaZonaList_Result> udf_CertificadosInaebaZonaList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_CertificadosInaebaZonaList_Result>("[Entities].[udf_CertificadosInaebaZonaList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_IncumplimientoActividadesPeriodoList")]
        public virtual IQueryable<udf_IncumplimientoActividadesPeriodoList_Result> udf_IncumplimientoActividadesPeriodoList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_IncumplimientoActividadesPeriodoList_Result>("[Entities].[udf_IncumplimientoActividadesPeriodoList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_IncumplimientoActividadesPeriodoRegionList")]
        public virtual IQueryable<udf_IncumplimientoActividadesPeriodoRegionList_Result> udf_IncumplimientoActividadesPeriodoRegionList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_IncumplimientoActividadesPeriodoRegionList_Result>("[Entities].[udf_IncumplimientoActividadesPeriodoRegionList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_IncumplimientoActividadesPeriodoRegionZonaList")]
        public virtual IQueryable<udf_IncumplimientoActividadesPeriodoRegionZonaList_Result> udf_IncumplimientoActividadesPeriodoRegionZonaList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_IncumplimientoActividadesPeriodoRegionZonaList_Result>("[Entities].[udf_IncumplimientoActividadesPeriodoRegionZonaList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_IncumplimientoActividadesPeriodoZonaActividadList")]
        public virtual IQueryable<udf_IncumplimientoActividadesPeriodoZonaActividadList_Result> udf_IncumplimientoActividadesPeriodoZonaActividadList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_IncumplimientoActividadesPeriodoZonaActividadList_Result>("[Entities].[udf_IncumplimientoActividadesPeriodoZonaActividadList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_ModulosSeguridadxRol")]
        public virtual IQueryable<udf_ModulosSeguridadxRol_Result> udf_ModulosSeguridadxRol(Nullable<int> rol)
        {
            var rolParameter = rol.HasValue ?
                new ObjectParameter("Rol", rol) :
                new ObjectParameter("Rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_ModulosSeguridadxRol_Result>("[Entities].[udf_ModulosSeguridadxRol](@Rol)", rolParameter);
        }
    
        [DbFunction("Entities", "udf_PlanSemanalAprobarList")]
        public virtual IQueryable<udf_PlanSemanalAprobarList_Result> udf_PlanSemanalAprobarList(Nullable<int> p_UsuarioId, string p_Periodos, string p_TiposFigura, string p_NombresFigura)
        {
            var p_UsuarioIdParameter = p_UsuarioId.HasValue ?
                new ObjectParameter("p_UsuarioId", p_UsuarioId) :
                new ObjectParameter("p_UsuarioId", typeof(int));
    
            var p_PeriodosParameter = p_Periodos != null ?
                new ObjectParameter("p_Periodos", p_Periodos) :
                new ObjectParameter("p_Periodos", typeof(string));
    
            var p_TiposFiguraParameter = p_TiposFigura != null ?
                new ObjectParameter("p_TiposFigura", p_TiposFigura) :
                new ObjectParameter("p_TiposFigura", typeof(string));
    
            var p_NombresFiguraParameter = p_NombresFigura != null ?
                new ObjectParameter("p_NombresFigura", p_NombresFigura) :
                new ObjectParameter("p_NombresFigura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_PlanSemanalAprobarList_Result>("[Entities].[udf_PlanSemanalAprobarList](@p_UsuarioId, @p_Periodos, @p_TiposFigura, @p_NombresFigura)", p_UsuarioIdParameter, p_PeriodosParameter, p_TiposFiguraParameter, p_NombresFiguraParameter);
        }
    
        [DbFunction("Entities", "udf_PlanSemanalIncidenciasList")]
        public virtual IQueryable<udf_PlanSemanalIncidenciasList_Result> udf_PlanSemanalIncidenciasList(Nullable<int> p_UsuarioId, string p_Periodos, string p_TiposFigura, string p_NombresFigura, string p_TipoActvidades)
        {
            var p_UsuarioIdParameter = p_UsuarioId.HasValue ?
                new ObjectParameter("p_UsuarioId", p_UsuarioId) :
                new ObjectParameter("p_UsuarioId", typeof(int));
    
            var p_PeriodosParameter = p_Periodos != null ?
                new ObjectParameter("p_Periodos", p_Periodos) :
                new ObjectParameter("p_Periodos", typeof(string));
    
            var p_TiposFiguraParameter = p_TiposFigura != null ?
                new ObjectParameter("p_TiposFigura", p_TiposFigura) :
                new ObjectParameter("p_TiposFigura", typeof(string));
    
            var p_NombresFiguraParameter = p_NombresFigura != null ?
                new ObjectParameter("p_NombresFigura", p_NombresFigura) :
                new ObjectParameter("p_NombresFigura", typeof(string));
    
            var p_TipoActvidadesParameter = p_TipoActvidades != null ?
                new ObjectParameter("p_TipoActvidades", p_TipoActvidades) :
                new ObjectParameter("p_TipoActvidades", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_PlanSemanalIncidenciasList_Result>("[Entities].[udf_PlanSemanalIncidenciasList](@p_UsuarioId, @p_Periodos, @p_TiposFigura, @p_NombresFigura, @p_TipoActvidades)", p_UsuarioIdParameter, p_PeriodosParameter, p_TiposFiguraParameter, p_NombresFiguraParameter, p_TipoActvidadesParameter);
        }
    
        [DbFunction("Entities", "udf_PlanSemanalList")]
        public virtual IQueryable<udf_PlanSemanalList_Result> udf_PlanSemanalList(Nullable<int> p_UsuarioId)
        {
            var p_UsuarioIdParameter = p_UsuarioId.HasValue ?
                new ObjectParameter("p_UsuarioId", p_UsuarioId) :
                new ObjectParameter("p_UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_PlanSemanalList_Result>("[Entities].[udf_PlanSemanalList](@p_UsuarioId)", p_UsuarioIdParameter);
        }
    
        [DbFunction("Entities", "udf_PlanSemanalValidarList")]
        public virtual IQueryable<udf_PlanSemanalValidarList_Result> udf_PlanSemanalValidarList(Nullable<int> p_UsuarioId, string p_Periodos, string p_TiposFigura, string p_NombresFigura)
        {
            var p_UsuarioIdParameter = p_UsuarioId.HasValue ?
                new ObjectParameter("p_UsuarioId", p_UsuarioId) :
                new ObjectParameter("p_UsuarioId", typeof(int));
    
            var p_PeriodosParameter = p_Periodos != null ?
                new ObjectParameter("p_Periodos", p_Periodos) :
                new ObjectParameter("p_Periodos", typeof(string));
    
            var p_TiposFiguraParameter = p_TiposFigura != null ?
                new ObjectParameter("p_TiposFigura", p_TiposFigura) :
                new ObjectParameter("p_TiposFigura", typeof(string));
    
            var p_NombresFiguraParameter = p_NombresFigura != null ?
                new ObjectParameter("p_NombresFigura", p_NombresFigura) :
                new ObjectParameter("p_NombresFigura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_PlanSemanalValidarList_Result>("[Entities].[udf_PlanSemanalValidarList](@p_UsuarioId, @p_Periodos, @p_TiposFigura, @p_NombresFigura)", p_UsuarioIdParameter, p_PeriodosParameter, p_TiposFiguraParameter, p_NombresFiguraParameter);
        }
    
        [DbFunction("Entities", "udf_PreregistrosIncorporadosBaseList")]
        public virtual IQueryable<udf_PreregistrosIncorporadosBaseList_Result> udf_PreregistrosIncorporadosBaseList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_PreregistrosIncorporadosBaseList_Result>("[Entities].[udf_PreregistrosIncorporadosBaseList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_PreregistrosIncorporadosBaseRegionList")]
        public virtual IQueryable<udf_PreregistrosIncorporadosBaseRegionList_Result> udf_PreregistrosIncorporadosBaseRegionList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_PreregistrosIncorporadosBaseRegionList_Result>("[Entities].[udf_PreregistrosIncorporadosBaseRegionList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_PreregistrosIncorporadosPeriodoFiguraEducandoList")]
        public virtual IQueryable<udf_PreregistrosIncorporadosPeriodoFiguraEducandoList_Result> udf_PreregistrosIncorporadosPeriodoFiguraEducandoList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_PreregistrosIncorporadosPeriodoFiguraEducandoList_Result>("[Entities].[udf_PreregistrosIncorporadosPeriodoFiguraEducandoList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_PreregistrosIncorporadosPeriodoFiguraList")]
        public virtual IQueryable<udf_PreregistrosIncorporadosPeriodoFiguraList_Result> udf_PreregistrosIncorporadosPeriodoFiguraList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_PreregistrosIncorporadosPeriodoFiguraList_Result>("[Entities].[udf_PreregistrosIncorporadosPeriodoFiguraList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_PreregistrosIncorporadosZonaList")]
        public virtual IQueryable<udf_PreregistrosIncorporadosZonaList_Result> udf_PreregistrosIncorporadosZonaList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_PreregistrosIncorporadosZonaList_Result>("[Entities].[udf_PreregistrosIncorporadosZonaList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoAprobacionBaseList")]
        public virtual IQueryable<udf_RechazoAprobacionBaseList_Result> udf_RechazoAprobacionBaseList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoAprobacionBaseList_Result>("[Entities].[udf_RechazoAprobacionBaseList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoAprobacionRegionList")]
        public virtual IQueryable<udf_RechazoAprobacionRegionList_Result> udf_RechazoAprobacionRegionList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoAprobacionRegionList_Result>("[Entities].[udf_RechazoAprobacionRegionList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoAprobacionZonaFiguraNombreAprobacionAct")]
        public virtual IQueryable<udf_RechazoAprobacionZonaFiguraNombreAprobacionAct_Result> udf_RechazoAprobacionZonaFiguraNombreAprobacionAct(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoAprobacionZonaFiguraNombreAprobacionAct_Result>("[Entities].[udf_RechazoAprobacionZonaFiguraNombreAprobacionAct](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoAprobacionZonaFiguraNombreAprobacionList")]
        public virtual IQueryable<udf_RechazoAprobacionZonaFiguraNombreAprobacionList_Result> udf_RechazoAprobacionZonaFiguraNombreAprobacionList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoAprobacionZonaFiguraNombreAprobacionList_Result>("[Entities].[udf_RechazoAprobacionZonaFiguraNombreAprobacionList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoAprobacionZonaList")]
        public virtual IQueryable<udf_RechazoAprobacionZonaList_Result> udf_RechazoAprobacionZonaList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoAprobacionZonaList_Result>("[Entities].[udf_RechazoAprobacionZonaList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoValidacionBaseList")]
        public virtual IQueryable<udf_RechazoValidacionBaseList_Result> udf_RechazoValidacionBaseList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoValidacionBaseList_Result>("[Entities].[udf_RechazoValidacionBaseList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoValidacionRegionList")]
        public virtual IQueryable<udf_RechazoValidacionRegionList_Result> udf_RechazoValidacionRegionList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoValidacionRegionList_Result>("[Entities].[udf_RechazoValidacionRegionList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoValidacionZonaFiguraNombreValidacion")]
        public virtual IQueryable<udf_RechazoValidacionZonaFiguraNombreValidacion_Result> udf_RechazoValidacionZonaFiguraNombreValidacion(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoValidacionZonaFiguraNombreValidacion_Result>("[Entities].[udf_RechazoValidacionZonaFiguraNombreValidacion](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoValidacionZonaFiguraNombreValidacionAct")]
        public virtual IQueryable<udf_RechazoValidacionZonaFiguraNombreValidacionAct_Result> udf_RechazoValidacionZonaFiguraNombreValidacionAct(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoValidacionZonaFiguraNombreValidacionAct_Result>("[Entities].[udf_RechazoValidacionZonaFiguraNombreValidacionAct](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    
        [DbFunction("Entities", "udf_RechazoValidacionZonaList")]
        public virtual IQueryable<udf_RechazoValidacionZonaList_Result> udf_RechazoValidacionZonaList(string p_idPeriodo, string p_Region, string p_Zona, string p_TipoActividad)
        {
            var p_idPeriodoParameter = p_idPeriodo != null ?
                new ObjectParameter("p_idPeriodo", p_idPeriodo) :
                new ObjectParameter("p_idPeriodo", typeof(string));
    
            var p_RegionParameter = p_Region != null ?
                new ObjectParameter("p_Region", p_Region) :
                new ObjectParameter("p_Region", typeof(string));
    
            var p_ZonaParameter = p_Zona != null ?
                new ObjectParameter("p_Zona", p_Zona) :
                new ObjectParameter("p_Zona", typeof(string));
    
            var p_TipoActividadParameter = p_TipoActividad != null ?
                new ObjectParameter("p_TipoActividad", p_TipoActividad) :
                new ObjectParameter("p_TipoActividad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<udf_RechazoValidacionZonaList_Result>("[Entities].[udf_RechazoValidacionZonaList](@p_idPeriodo, @p_Region, @p_Zona, @p_TipoActividad)", p_idPeriodoParameter, p_RegionParameter, p_ZonaParameter, p_TipoActividadParameter);
        }
    }
}
