//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mResetPassword
    {
        public System.Guid Id { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Liga { get; set; }
        public Nullable<int> EstatusId { get; set; }
    
        public virtual mUsuarios mUsuarios { get; set; }
    }
}
