//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculosSolicitudes
    {
        public int SolicitudVehiculoId { get; set; }
        public int VehiculoId { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public Nullable<System.DateTime> FechaUsoInicio { get; set; }
        public string KilometrajeInicio { get; set; }
        public string KilometrajeFin { get; set; }
        public Nullable<System.DateTime> FechaUsoFin { get; set; }
        public string DescripcionActividad { get; set; }
        public Nullable<int> CirculoEstudioId { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<byte> EstatusSolicitudVehiculoId { get; set; }
        public string MotivoAsignacion { get; set; }
        public Nullable<int> AutorizadoPorId { get; set; }
        public Nullable<int> SolicitadoPorId { get; set; }
    
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
