//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculosCondicionesDetalles
    {
        public int VehiculoCondicionDetalleId { get; set; }
        public string Diagnostico { get; set; }
        public Nullable<int> VehiculoCondicionId { get; set; }
        public Nullable<byte> VehiculoCondicionTipoId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> UsuarioModificoId { get; set; }
        public Nullable<int> UsuarioCreoId { get; set; }
    
        public virtual VehiculosCondiciones VehiculosCondiciones { get; set; }
        public virtual VehiculosCondicionesTipos VehiculosCondicionesTipos { get; set; }
    }
}
