//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saptra.Web.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string btnCerrar {
            get {
                return ResourceManager.GetString("btnCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar.
        /// </summary>
        public static string btnCopy {
            get {
                return ResourceManager.GetString("btnCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Import settings.
        /// </summary>
        public static string btnCopyConfiguration {
            get {
                return ResourceManager.GetString("btnCopyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string btnEditar {
            get {
                return ResourceManager.GetString("btnEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de....
        /// </summary>
        public static string menuAbout {
            get {
                return ResourceManager.GetString("menuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aprobación Plan Semanal.
        /// </summary>
        public static string menuAprobacionPlan {
            get {
                return ResourceManager.GetString("menuAprobacionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capturar Educandos Captados.
        /// </summary>
        public static string menuCapturaCaptados {
            get {
                return ResourceManager.GetString("menuCapturaCaptados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de certificados entregados VS programados.
        /// </summary>
        public static string menuCertificados {
            get {
                return ResourceManager.GetString("menuCertificados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta Plan Semanal.
        /// </summary>
        public static string menuConsultaPlanes {
            get {
                return ResourceManager.GetString("menuConsultaPlanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Educandos captados VS pre registrados.
        /// </summary>
        public static string menuEducandos {
            get {
                return ResourceManager.GetString("menuEducandos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string menuEspanol {
            get {
                return ResourceManager.GetString("menuEspanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Figuras.
        /// </summary>
        public static string menuFiguras {
            get {
                return ResourceManager.GetString("menuFiguras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Figuras con reincidencias negativas.
        /// </summary>
        public static string menuFigurasConReincidencias {
            get {
                return ResourceManager.GetString("menuFigurasConReincidencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Figuras reincidentes en rechazo de plan semanal.
        /// </summary>
        public static string menuFigurasReincidentes {
            get {
                return ResourceManager.GetString("menuFigurasReincidentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biblioteca.
        /// </summary>
        public static string menuGrupoBiblioteca {
            get {
                return ResourceManager.GetString("menuGrupoBiblioteca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicadores.
        /// </summary>
        public static string menuGrupoIndicadores {
            get {
                return ResourceManager.GetString("menuGrupoIndicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenes de Compra.
        /// </summary>
        public static string menuGrupoOrdenesCompra {
            get {
                return ResourceManager.GetString("menuGrupoOrdenesCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plan Semanal.
        /// </summary>
        public static string menuGrupoPlanSemanal {
            get {
                return ResourceManager.GetString("menuGrupoPlanSemanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimiento Plan.
        /// </summary>
        public static string menuGrupoSeguimientoPlan {
            get {
                return ResourceManager.GetString("menuGrupoSeguimientoPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        public static string menuGrupoSeguridad {
            get {
                return ResourceManager.GetString("menuGrupoSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incumplimiento de actividades por periodo.
        /// </summary>
        public static string menuIncumplimientoActividades {
            get {
                return ResourceManager.GetString("menuIncumplimientoActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string menuIngles {
            get {
                return ResourceManager.GetString("menuIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        public static string menuLoading {
            get {
                return ResourceManager.GetString("menuLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenes de Compra.
        /// </summary>
        public static string menuOrdenesCompra {
            get {
                return ResourceManager.GetString("menuOrdenesCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguimiento de envios.
        /// </summary>
        public static string menuOrdenesCompraEnviado {
            get {
                return ResourceManager.GetString("menuOrdenesCompraEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodos.
        /// </summary>
        public static string menuPeriodos {
            get {
                return ResourceManager.GetString("menuPeriodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Captura Plan Semanal.
        /// </summary>
        public static string menuRegistroPlan {
            get {
                return ResourceManager.GetString("menuRegistroPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte Envios.
        /// </summary>
        public static string menuReporteEnvios {
            get {
                return ResourceManager.GetString("menuReporteEnvios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles.
        /// </summary>
        public static string menuRoles {
            get {
                return ResourceManager.GetString("menuRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles.
        /// </summary>
        public static string menuSeguridadRoles {
            get {
                return ResourceManager.GetString("menuSeguridadRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        public static string menuSeguridadUsuarios {
            get {
                return ResourceManager.GetString("menuSeguridadUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Actividades.
        /// </summary>
        public static string menuTiposActividades {
            get {
                return ResourceManager.GetString("menuTiposActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string menuUsuarios {
            get {
                return ResourceManager.GetString("menuUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validación Plan Semanal.
        /// </summary>
        public static string menuValidacionPlan {
            get {
                return ResourceManager.GetString("menuValidacionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar Envio.
        /// </summary>
        public static string menuVerificarEnvio {
            get {
                return ResourceManager.GetString("menuVerificarEnvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List.
        /// </summary>
        public static string titleList {
            get {
                return ResourceManager.GetString("titleList", resourceCulture);
            }
        }
    }
}
